# Generated by Django 4.2.1 on 2023-05-12 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='num_room',
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 11, 19, 13, 114335, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=7),
            preserve_default=False,
        ),
    ]
