# Generated by Django 4.2.1 on 2023-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_delete_availability_delete_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_room',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
