# Generated by Django 4.2.1 on 2023-05-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_num_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='room.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(upload_to='room_images'),
        ),
    ]
