# Generated by Django 4.2.1 on 2023-05-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='num_room',
        ),
    ]
