# Generated by Django 4.2.1 on 2023-05-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_num_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
