# Generated by Django 4.2.1 on 2023-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_is_cancelled_alter_bookingroom_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
    ]
