# Generated by Django 4.2.1 on 2023-05-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_is_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_history',
        ),
    ]
